// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: AttributesMap.proto

package com.zibea.recommendations.webserver.core.dao.proto;

public final class AttributesMapProto {
  private AttributesMapProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface MapOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // repeated .com.zibea.recommendations.webserver.dataaccess.proto.Map.KeyValue nodes = 1;
    java.util.List<com.zibea.recommendations.webserver.core.dao.proto.AttributesMapProto.Map.KeyValue> 
        getNodesList();
    com.zibea.recommendations.webserver.core.dao.proto.AttributesMapProto.Map.KeyValue getNodes(int index);
    int getNodesCount();
    java.util.List<? extends com.zibea.recommendations.webserver.core.dao.proto.AttributesMapProto.Map.KeyValueOrBuilder> 
        getNodesOrBuilderList();
    com.zibea.recommendations.webserver.core.dao.proto.AttributesMapProto.Map.KeyValueOrBuilder getNodesOrBuilder(
            int index);
  }
  public static final class Map extends
      com.google.protobuf.GeneratedMessage
      implements MapOrBuilder {
    // Use Map.newBuilder() to construct.
    private Map(Builder builder) {
      super(builder);
    }
    private Map(boolean noInit) {}
    
    private static final Map defaultInstance;
    public static Map getDefaultInstance() {
      return defaultInstance;
    }
    
    public Map getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return internal_static_com_zibea_recommendations_webserver_dataaccess_proto_Map_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return internal_static_com_zibea_recommendations_webserver_dataaccess_proto_Map_fieldAccessorTable;
    }
    
    public interface KeyValueOrBuilder
        extends com.google.protobuf.MessageOrBuilder {
      
      // required int32 key = 1;
      boolean hasKey();
      int getKey();
      
      // required string value = 2;
      boolean hasValue();
      String getValue();
    }
    public static final class KeyValue extends
        com.google.protobuf.GeneratedMessage
        implements KeyValueOrBuilder {
      // Use KeyValue.newBuilder() to construct.
      private KeyValue(Builder builder) {
        super(builder);
      }
      private KeyValue(boolean noInit) {}
      
      private static final KeyValue defaultInstance;
      public static KeyValue getDefaultInstance() {
        return defaultInstance;
      }
      
      public KeyValue getDefaultInstanceForType() {
        return defaultInstance;
      }
      
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return internal_static_com_zibea_recommendations_webserver_dataaccess_proto_Map_KeyValue_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return internal_static_com_zibea_recommendations_webserver_dataaccess_proto_Map_KeyValue_fieldAccessorTable;
      }
      
      private int bitField0_;
      // required int32 key = 1;
      public static final int KEY_FIELD_NUMBER = 1;
      private int key_;
      public boolean hasKey() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public int getKey() {
        return key_;
      }
      
      // required string value = 2;
      public static final int VALUE_FIELD_NUMBER = 2;
      private Object value_;
      public boolean hasValue() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      public String getValue() {
        Object ref = value_;
        if (ref instanceof String) {
          return (String) ref;
        } else {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          if (com.google.protobuf.Internal.isValidUtf8(bs)) {
            value_ = s;
          }
          return s;
        }
      }
      private com.google.protobuf.ByteString getValueBytes() {
        Object ref = value_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b =
              com.google.protobuf.ByteString.copyFromUtf8((String) ref);
          value_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }

      private void initFields() {
        key_ = 0;
        value_ = "";
      }
      private byte memoizedIsInitialized = -1;
      public final boolean isInitialized() {
        byte isInitialized = memoizedIsInitialized;
        if (isInitialized != -1) return isInitialized == 1;

        if (!hasKey()) {
          memoizedIsInitialized = 0;
          return false;
        }
        if (!hasValue()) {
          memoizedIsInitialized = 0;
          return false;
        }
        memoizedIsInitialized = 1;
        return true;
      }

      public void writeTo(com.google.protobuf.CodedOutputStream output)
                          throws java.io.IOException {
        getSerializedSize();
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          output.writeInt32(1, key_);
        }
        if (((bitField0_ & 0x00000002) == 0x00000002)) {
          output.writeBytes(2, getValueBytes());
        }
        getUnknownFields().writeTo(output);
      }

      private int memoizedSerializedSize = -1;
      public int getSerializedSize() {
        int size = memoizedSerializedSize;
        if (size != -1) return size;

        size = 0;
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          size += com.google.protobuf.CodedOutputStream
            .computeInt32Size(1, key_);
        }
        if (((bitField0_ & 0x00000002) == 0x00000002)) {
          size += com.google.protobuf.CodedOutputStream
            .computeBytesSize(2, getValueBytes());
        }
        size += getUnknownFields().getSerializedSize();
        memoizedSerializedSize = size;
        return size;
      }

      private static final long serialVersionUID = 0L;
      @Override
      protected Object writeReplace()
          throws java.io.ObjectStreamException {
        return super.writeReplace();
      }

      public static com.zibea.recommendations.webserver.core.dao.proto.AttributesMapProto.Map.KeyValue parseFrom(
          com.google.protobuf.ByteString data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return newBuilder().mergeFrom(data).buildParsed();
      }
      public static com.zibea.recommendations.webserver.core.dao.proto.AttributesMapProto.Map.KeyValue parseFrom(
          com.google.protobuf.ByteString data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return newBuilder().mergeFrom(data, extensionRegistry)
                 .buildParsed();
      }
      public static com.zibea.recommendations.webserver.core.dao.proto.AttributesMapProto.Map.KeyValue parseFrom(byte[] data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return newBuilder().mergeFrom(data).buildParsed();
      }
      public static com.zibea.recommendations.webserver.core.dao.proto.AttributesMapProto.Map.KeyValue parseFrom(
          byte[] data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return newBuilder().mergeFrom(data, extensionRegistry)
                 .buildParsed();
      }
      public static com.zibea.recommendations.webserver.core.dao.proto.AttributesMapProto.Map.KeyValue parseFrom(java.io.InputStream input)
          throws java.io.IOException {
        return newBuilder().mergeFrom(input).buildParsed();
      }
      public static com.zibea.recommendations.webserver.core.dao.proto.AttributesMapProto.Map.KeyValue parseFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return newBuilder().mergeFrom(input, extensionRegistry)
                 .buildParsed();
      }
      public static com.zibea.recommendations.webserver.core.dao.proto.AttributesMapProto.Map.KeyValue parseDelimitedFrom(java.io.InputStream input)
          throws java.io.IOException {
        Builder builder = newBuilder();
        if (builder.mergeDelimitedFrom(input)) {
          return builder.buildParsed();
        } else {
          return null;
        }
      }
      public static com.zibea.recommendations.webserver.core.dao.proto.AttributesMapProto.Map.KeyValue parseDelimitedFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        Builder builder = newBuilder();
        if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
          return builder.buildParsed();
        } else {
          return null;
        }
      }
      public static com.zibea.recommendations.webserver.core.dao.proto.AttributesMapProto.Map.KeyValue parseFrom(
          com.google.protobuf.CodedInputStream input)
          throws java.io.IOException {
        return newBuilder().mergeFrom(input).buildParsed();
      }
      public static com.zibea.recommendations.webserver.core.dao.proto.AttributesMapProto.Map.KeyValue parseFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return newBuilder().mergeFrom(input, extensionRegistry)
                 .buildParsed();
      }

      public static Builder newBuilder() { return Builder.create(); }
      public Builder newBuilderForType() { return newBuilder(); }
      public static Builder newBuilder(com.zibea.recommendations.webserver.core.dao.proto.AttributesMapProto.Map.KeyValue prototype) {
        return newBuilder().mergeFrom(prototype);
      }
      public Builder toBuilder() { return newBuilder(this); }

      @Override
      protected Builder newBuilderForType(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        Builder builder = new Builder(parent);
        return builder;
      }
      public static final class Builder extends
          com.google.protobuf.GeneratedMessage.Builder<Builder>
         implements com.zibea.recommendations.webserver.core.dao.proto.AttributesMapProto.Map.KeyValueOrBuilder {
        public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
          return internal_static_com_zibea_recommendations_webserver_dataaccess_proto_Map_KeyValue_descriptor;
        }

        protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
            internalGetFieldAccessorTable() {
          return internal_static_com_zibea_recommendations_webserver_dataaccess_proto_Map_KeyValue_fieldAccessorTable;
        }

        // Construct using com.zibea.recommendations.webserver.core.dao.proto.AttributesMapProto.Map.KeyValue.newBuilder()
        private Builder() {
          maybeForceBuilderInitialization();
        }

        private Builder(BuilderParent parent) {
          super(parent);
          maybeForceBuilderInitialization();
        }
        private void maybeForceBuilderInitialization() {
          if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          }
        }
        private static Builder create() {
          return new Builder();
        }

        public Builder clear() {
          super.clear();
          key_ = 0;
          bitField0_ = (bitField0_ & ~0x00000001);
          value_ = "";
          bitField0_ = (bitField0_ & ~0x00000002);
          return this;
        }

        public Builder clone() {
          return create().mergeFrom(buildPartial());
        }

        public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
          return com.zibea.recommendations.webserver.core.dao.proto.AttributesMapProto.Map.KeyValue.getDescriptor();
        }

        public com.zibea.recommendations.webserver.core.dao.proto.AttributesMapProto.Map.KeyValue getDefaultInstanceForType() {
          return getDefaultInstance();
        }

        public com.zibea.recommendations.webserver.core.dao.proto.AttributesMapProto.Map.KeyValue build() {
          com.zibea.recommendations.webserver.core.dao.proto.AttributesMapProto.Map.KeyValue result = buildPartial();
          if (!result.isInitialized()) {
            throw newUninitializedMessageException(result);
          }
          return result;
        }

        private com.zibea.recommendations.webserver.core.dao.proto.AttributesMapProto.Map.KeyValue buildParsed()
            throws com.google.protobuf.InvalidProtocolBufferException {
          com.zibea.recommendations.webserver.core.dao.proto.AttributesMapProto.Map.KeyValue result = buildPartial();
          if (!result.isInitialized()) {
            throw newUninitializedMessageException(
              result).asInvalidProtocolBufferException();
          }
          return result;
        }

        public com.zibea.recommendations.webserver.core.dao.proto.AttributesMapProto.Map.KeyValue buildPartial() {
          com.zibea.recommendations.webserver.core.dao.proto.AttributesMapProto.Map.KeyValue result = new com.zibea.recommendations.webserver.core.dao.proto.AttributesMapProto.Map.KeyValue(this);
          int from_bitField0_ = bitField0_;
          int to_bitField0_ = 0;
          if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
            to_bitField0_ |= 0x00000001;
          }
          result.key_ = key_;
          if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
            to_bitField0_ |= 0x00000002;
          }
          result.value_ = value_;
          result.bitField0_ = to_bitField0_;
          onBuilt();
          return result;
        }

        public Builder mergeFrom(com.google.protobuf.Message other) {
          if (other instanceof com.zibea.recommendations.webserver.core.dao.proto.AttributesMapProto.Map.KeyValue) {
            return mergeFrom((com.zibea.recommendations.webserver.core.dao.proto.AttributesMapProto.Map.KeyValue)other);
          } else {
            super.mergeFrom(other);
            return this;
          }
        }

        public Builder mergeFrom(com.zibea.recommendations.webserver.core.dao.proto.AttributesMapProto.Map.KeyValue other) {
          if (other == getDefaultInstance()) return this;
          if (other.hasKey()) {
            setKey(other.getKey());
          }
          if (other.hasValue()) {
            setValue(other.getValue());
          }
          this.mergeUnknownFields(other.getUnknownFields());
          return this;
        }

        public final boolean isInitialized() {
          if (!hasKey()) {

            return false;
          }
          if (!hasValue()) {

            return false;
          }
          return true;
        }

        public Builder mergeFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
          com.google.protobuf.UnknownFieldSet.Builder unknownFields =
            com.google.protobuf.UnknownFieldSet.newBuilder(
              this.getUnknownFields());
          while (true) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              default: {
                if (!parseUnknownField(input, unknownFields,
                                       extensionRegistry, tag)) {
                  this.setUnknownFields(unknownFields.build());
                  onChanged();
                  return this;
                }
                break;
              }
              case 8: {
                bitField0_ |= 0x00000001;
                key_ = input.readInt32();
                break;
              }
              case 18: {
                bitField0_ |= 0x00000002;
                value_ = input.readBytes();
                break;
              }
            }
          }
        }

        private int bitField0_;

        // required int32 key = 1;
        private int key_ ;
        public boolean hasKey() {
          return ((bitField0_ & 0x00000001) == 0x00000001);
        }
        public int getKey() {
          return key_;
        }
        public Builder setKey(int value) {
          bitField0_ |= 0x00000001;
          key_ = value;
          onChanged();
          return this;
        }
        public Builder clearKey() {
          bitField0_ = (bitField0_ & ~0x00000001);
          key_ = 0;
          onChanged();
          return this;
        }

        // required string value = 2;
        private Object value_ = "";
        public boolean hasValue() {
          return ((bitField0_ & 0x00000002) == 0x00000002);
        }
        public String getValue() {
          Object ref = value_;
          if (!(ref instanceof String)) {
            String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
            value_ = s;
            return s;
          } else {
            return (String) ref;
          }
        }
        public Builder setValue(String value) {
          if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
          value_ = value;
          onChanged();
          return this;
        }
        public Builder clearValue() {
          bitField0_ = (bitField0_ & ~0x00000002);
          value_ = getDefaultInstance().getValue();
          onChanged();
          return this;
        }
        void setValue(com.google.protobuf.ByteString value) {
          bitField0_ |= 0x00000002;
          value_ = value;
          onChanged();
        }

        // @@protoc_insertion_point(builder_scope:com.zibea.recommendations.webserver.dataaccess.proto.Map.KeyValue)
      }

      static {
        defaultInstance = new KeyValue(true);
        defaultInstance.initFields();
      }

      // @@protoc_insertion_point(class_scope:com.zibea.recommendations.webserver.dataaccess.proto.Map.KeyValue)
    }

    // repeated .com.zibea.recommendations.webserver.dataaccess.proto.Map.KeyValue nodes = 1;
    public static final int NODES_FIELD_NUMBER = 1;
    private java.util.List<com.zibea.recommendations.webserver.core.dao.proto.AttributesMapProto.Map.KeyValue> nodes_;
    public java.util.List<com.zibea.recommendations.webserver.core.dao.proto.AttributesMapProto.Map.KeyValue> getNodesList() {
      return nodes_;
    }
    public java.util.List<? extends com.zibea.recommendations.webserver.core.dao.proto.AttributesMapProto.Map.KeyValueOrBuilder>
        getNodesOrBuilderList() {
      return nodes_;
    }
    public int getNodesCount() {
      return nodes_.size();
    }
    public com.zibea.recommendations.webserver.core.dao.proto.AttributesMapProto.Map.KeyValue getNodes(int index) {
      return nodes_.get(index);
    }
    public com.zibea.recommendations.webserver.core.dao.proto.AttributesMapProto.Map.KeyValueOrBuilder getNodesOrBuilder(
        int index) {
      return nodes_.get(index);
    }

    private void initFields() {
      nodes_ = java.util.Collections.emptyList();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      for (int i = 0; i < getNodesCount(); i++) {
        if (!getNodes(i).isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      for (int i = 0; i < nodes_.size(); i++) {
        output.writeMessage(1, nodes_.get(i));
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < nodes_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, nodes_.get(i));
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @Override
    protected Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.zibea.recommendations.webserver.core.dao.proto.AttributesMapProto.Map parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.zibea.recommendations.webserver.core.dao.proto.AttributesMapProto.Map parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.zibea.recommendations.webserver.core.dao.proto.AttributesMapProto.Map parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.zibea.recommendations.webserver.core.dao.proto.AttributesMapProto.Map parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.zibea.recommendations.webserver.core.dao.proto.AttributesMapProto.Map parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.zibea.recommendations.webserver.core.dao.proto.AttributesMapProto.Map parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.zibea.recommendations.webserver.core.dao.proto.AttributesMapProto.Map parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.zibea.recommendations.webserver.core.dao.proto.AttributesMapProto.Map parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.zibea.recommendations.webserver.core.dao.proto.AttributesMapProto.Map parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.zibea.recommendations.webserver.core.dao.proto.AttributesMapProto.Map parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.zibea.recommendations.webserver.core.dao.proto.AttributesMapProto.Map prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.zibea.recommendations.webserver.core.dao.proto.AttributesMapProto.MapOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return internal_static_com_zibea_recommendations_webserver_dataaccess_proto_Map_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return internal_static_com_zibea_recommendations_webserver_dataaccess_proto_Map_fieldAccessorTable;
      }

      // Construct using com.zibea.recommendations.webserver.core.dao.proto.AttributesMapProto.Map.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getNodesFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        if (nodesBuilder_ == null) {
          nodes_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          nodesBuilder_.clear();
        }
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.zibea.recommendations.webserver.core.dao.proto.AttributesMapProto.Map.getDescriptor();
      }

      public com.zibea.recommendations.webserver.core.dao.proto.AttributesMapProto.Map getDefaultInstanceForType() {
        return getDefaultInstance();
      }

      public com.zibea.recommendations.webserver.core.dao.proto.AttributesMapProto.Map build() {
        com.zibea.recommendations.webserver.core.dao.proto.AttributesMapProto.Map result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      private com.zibea.recommendations.webserver.core.dao.proto.AttributesMapProto.Map buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        com.zibea.recommendations.webserver.core.dao.proto.AttributesMapProto.Map result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }

      public com.zibea.recommendations.webserver.core.dao.proto.AttributesMapProto.Map buildPartial() {
        com.zibea.recommendations.webserver.core.dao.proto.AttributesMapProto.Map result = new com.zibea.recommendations.webserver.core.dao.proto.AttributesMapProto.Map(this);
        int from_bitField0_ = bitField0_;
        if (nodesBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001)) {
            nodes_ = java.util.Collections.unmodifiableList(nodes_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.nodes_ = nodes_;
        } else {
          result.nodes_ = nodesBuilder_.build();
        }
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.zibea.recommendations.webserver.core.dao.proto.AttributesMapProto.Map) {
          return mergeFrom((com.zibea.recommendations.webserver.core.dao.proto.AttributesMapProto.Map)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.zibea.recommendations.webserver.core.dao.proto.AttributesMapProto.Map other) {
        if (other == getDefaultInstance()) return this;
        if (nodesBuilder_ == null) {
          if (!other.nodes_.isEmpty()) {
            if (nodes_.isEmpty()) {
              nodes_ = other.nodes_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureNodesIsMutable();
              nodes_.addAll(other.nodes_);
            }
            onChanged();
          }
        } else {
          if (!other.nodes_.isEmpty()) {
            if (nodesBuilder_.isEmpty()) {
              nodesBuilder_.dispose();
              nodesBuilder_ = null;
              nodes_ = other.nodes_;
              bitField0_ = (bitField0_ & ~0x00000001);
              nodesBuilder_ =
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getNodesFieldBuilder() : null;
            } else {
              nodesBuilder_.addAllMessages(other.nodes_);
            }
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        for (int i = 0; i < getNodesCount(); i++) {
          if (!getNodes(i).isInitialized()) {

            return false;
          }
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 10: {
              com.zibea.recommendations.webserver.core.dao.proto.AttributesMapProto.Map.KeyValue.Builder subBuilder = com.zibea.recommendations.webserver.core.dao.proto.AttributesMapProto.Map.KeyValue.newBuilder();
              input.readMessage(subBuilder, extensionRegistry);
              addNodes(subBuilder.buildPartial());
              break;
            }
          }
        }
      }

      private int bitField0_;

      // repeated .com.zibea.recommendations.webserver.dataaccess.proto.Map.KeyValue nodes = 1;
      private java.util.List<com.zibea.recommendations.webserver.core.dao.proto.AttributesMapProto.Map.KeyValue> nodes_ =
        java.util.Collections.emptyList();
      private void ensureNodesIsMutable() {
        if (!((bitField0_ & 0x00000001) == 0x00000001)) {
          nodes_ = new java.util.ArrayList<com.zibea.recommendations.webserver.core.dao.proto.AttributesMapProto.Map.KeyValue>(nodes_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilder<
          com.zibea.recommendations.webserver.core.dao.proto.AttributesMapProto.Map.KeyValue, com.zibea.recommendations.webserver.core.dao.proto.AttributesMapProto.Map.KeyValue.Builder, com.zibea.recommendations.webserver.core.dao.proto.AttributesMapProto.Map.KeyValueOrBuilder> nodesBuilder_;

      public java.util.List<com.zibea.recommendations.webserver.core.dao.proto.AttributesMapProto.Map.KeyValue> getNodesList() {
        if (nodesBuilder_ == null) {
          return java.util.Collections.unmodifiableList(nodes_);
        } else {
          return nodesBuilder_.getMessageList();
        }
      }
      public int getNodesCount() {
        if (nodesBuilder_ == null) {
          return nodes_.size();
        } else {
          return nodesBuilder_.getCount();
        }
      }
      public com.zibea.recommendations.webserver.core.dao.proto.AttributesMapProto.Map.KeyValue getNodes(int index) {
        if (nodesBuilder_ == null) {
          return nodes_.get(index);
        } else {
          return nodesBuilder_.getMessage(index);
        }
      }
      public Builder setNodes(
          int index, com.zibea.recommendations.webserver.core.dao.proto.AttributesMapProto.Map.KeyValue value) {
        if (nodesBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureNodesIsMutable();
          nodes_.set(index, value);
          onChanged();
        } else {
          nodesBuilder_.setMessage(index, value);
        }
        return this;
      }
      public Builder setNodes(
          int index, com.zibea.recommendations.webserver.core.dao.proto.AttributesMapProto.Map.KeyValue.Builder builderForValue) {
        if (nodesBuilder_ == null) {
          ensureNodesIsMutable();
          nodes_.set(index, builderForValue.build());
          onChanged();
        } else {
          nodesBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      public Builder addNodes(com.zibea.recommendations.webserver.core.dao.proto.AttributesMapProto.Map.KeyValue value) {
        if (nodesBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureNodesIsMutable();
          nodes_.add(value);
          onChanged();
        } else {
          nodesBuilder_.addMessage(value);
        }
        return this;
      }
      public Builder addNodes(
          int index, com.zibea.recommendations.webserver.core.dao.proto.AttributesMapProto.Map.KeyValue value) {
        if (nodesBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureNodesIsMutable();
          nodes_.add(index, value);
          onChanged();
        } else {
          nodesBuilder_.addMessage(index, value);
        }
        return this;
      }
      public Builder addNodes(
          com.zibea.recommendations.webserver.core.dao.proto.AttributesMapProto.Map.KeyValue.Builder builderForValue) {
        if (nodesBuilder_ == null) {
          ensureNodesIsMutable();
          nodes_.add(builderForValue.build());
          onChanged();
        } else {
          nodesBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      public Builder addNodes(
          int index, com.zibea.recommendations.webserver.core.dao.proto.AttributesMapProto.Map.KeyValue.Builder builderForValue) {
        if (nodesBuilder_ == null) {
          ensureNodesIsMutable();
          nodes_.add(index, builderForValue.build());
          onChanged();
        } else {
          nodesBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      public Builder addAllNodes(
          Iterable<? extends com.zibea.recommendations.webserver.core.dao.proto.AttributesMapProto.Map.KeyValue> values) {
        if (nodesBuilder_ == null) {
          ensureNodesIsMutable();
          super.addAll(values, nodes_);
          onChanged();
        } else {
          nodesBuilder_.addAllMessages(values);
        }
        return this;
      }
      public Builder clearNodes() {
        if (nodesBuilder_ == null) {
          nodes_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          nodesBuilder_.clear();
        }
        return this;
      }
      public Builder removeNodes(int index) {
        if (nodesBuilder_ == null) {
          ensureNodesIsMutable();
          nodes_.remove(index);
          onChanged();
        } else {
          nodesBuilder_.remove(index);
        }
        return this;
      }
      public com.zibea.recommendations.webserver.core.dao.proto.AttributesMapProto.Map.KeyValue.Builder getNodesBuilder(
          int index) {
        return getNodesFieldBuilder().getBuilder(index);
      }
      public com.zibea.recommendations.webserver.core.dao.proto.AttributesMapProto.Map.KeyValueOrBuilder getNodesOrBuilder(
          int index) {
        if (nodesBuilder_ == null) {
          return nodes_.get(index);  } else {
          return nodesBuilder_.getMessageOrBuilder(index);
        }
      }
      public java.util.List<? extends com.zibea.recommendations.webserver.core.dao.proto.AttributesMapProto.Map.KeyValueOrBuilder>
           getNodesOrBuilderList() {
        if (nodesBuilder_ != null) {
          return nodesBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(nodes_);
        }
      }
      public com.zibea.recommendations.webserver.core.dao.proto.AttributesMapProto.Map.KeyValue.Builder addNodesBuilder() {
        return getNodesFieldBuilder().addBuilder(
            com.zibea.recommendations.webserver.core.dao.proto.AttributesMapProto.Map.KeyValue.getDefaultInstance());
      }
      public com.zibea.recommendations.webserver.core.dao.proto.AttributesMapProto.Map.KeyValue.Builder addNodesBuilder(
          int index) {
        return getNodesFieldBuilder().addBuilder(
            index, com.zibea.recommendations.webserver.core.dao.proto.AttributesMapProto.Map.KeyValue.getDefaultInstance());
      }
      public java.util.List<com.zibea.recommendations.webserver.core.dao.proto.AttributesMapProto.Map.KeyValue.Builder>
           getNodesBuilderList() {
        return getNodesFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          com.zibea.recommendations.webserver.core.dao.proto.AttributesMapProto.Map.KeyValue, com.zibea.recommendations.webserver.core.dao.proto.AttributesMapProto.Map.KeyValue.Builder, com.zibea.recommendations.webserver.core.dao.proto.AttributesMapProto.Map.KeyValueOrBuilder>
          getNodesFieldBuilder() {
        if (nodesBuilder_ == null) {
          nodesBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              com.zibea.recommendations.webserver.core.dao.proto.AttributesMapProto.Map.KeyValue, com.zibea.recommendations.webserver.core.dao.proto.AttributesMapProto.Map.KeyValue.Builder, com.zibea.recommendations.webserver.core.dao.proto.AttributesMapProto.Map.KeyValueOrBuilder>(
                  nodes_,
                  ((bitField0_ & 0x00000001) == 0x00000001),
                  getParentForChildren(),
                  isClean());
          nodes_ = null;
        }
        return nodesBuilder_;
      }

      // @@protoc_insertion_point(builder_scope:com.zibea.recommendations.webserver.dataaccess.proto.Map)
    }

    static {
      defaultInstance = new Map(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:com.zibea.recommendations.webserver.dataaccess.proto.Map)
  }

  public interface AttributesMapOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required .com.zibea.recommendations.webserver.dataaccess.proto.Map attributes = 1;
    boolean hasAttributes();
    com.zibea.recommendations.webserver.core.dao.proto.AttributesMapProto.Map getAttributes();
    com.zibea.recommendations.webserver.core.dao.proto.AttributesMapProto.MapOrBuilder getAttributesOrBuilder();
  }
  public static final class AttributesMap extends
      com.google.protobuf.GeneratedMessage
      implements AttributesMapOrBuilder {
    // Use AttributesMap.newBuilder() to construct.
    private AttributesMap(Builder builder) {
      super(builder);
    }
    private AttributesMap(boolean noInit) {}

    private static final AttributesMap defaultInstance;
    public static AttributesMap getDefaultInstance() {
      return defaultInstance;
    }

    public AttributesMap getDefaultInstanceForType() {
      return defaultInstance;
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return internal_static_com_zibea_recommendations_webserver_dataaccess_proto_AttributesMap_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return internal_static_com_zibea_recommendations_webserver_dataaccess_proto_AttributesMap_fieldAccessorTable;
    }

    private int bitField0_;
    // required .com.zibea.recommendations.webserver.dataaccess.proto.Map attributes = 1;
    public static final int ATTRIBUTES_FIELD_NUMBER = 1;
    private com.zibea.recommendations.webserver.core.dao.proto.AttributesMapProto.Map attributes_;
    public boolean hasAttributes() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public com.zibea.recommendations.webserver.core.dao.proto.AttributesMapProto.Map getAttributes() {
      return attributes_;
    }
    public com.zibea.recommendations.webserver.core.dao.proto.AttributesMapProto.MapOrBuilder getAttributesOrBuilder() {
      return attributes_;
    }

    private void initFields() {
      attributes_ = com.zibea.recommendations.webserver.core.dao.proto.AttributesMapProto.Map.getDefaultInstance();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasAttributes()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!getAttributes().isInitialized()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeMessage(1, attributes_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, attributes_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @Override
    protected Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.zibea.recommendations.webserver.core.dao.proto.AttributesMapProto.AttributesMap parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.zibea.recommendations.webserver.core.dao.proto.AttributesMapProto.AttributesMap parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.zibea.recommendations.webserver.core.dao.proto.AttributesMapProto.AttributesMap parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.zibea.recommendations.webserver.core.dao.proto.AttributesMapProto.AttributesMap parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.zibea.recommendations.webserver.core.dao.proto.AttributesMapProto.AttributesMap parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.zibea.recommendations.webserver.core.dao.proto.AttributesMapProto.AttributesMap parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.zibea.recommendations.webserver.core.dao.proto.AttributesMapProto.AttributesMap parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.zibea.recommendations.webserver.core.dao.proto.AttributesMapProto.AttributesMap parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.zibea.recommendations.webserver.core.dao.proto.AttributesMapProto.AttributesMap parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.zibea.recommendations.webserver.core.dao.proto.AttributesMapProto.AttributesMap parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.zibea.recommendations.webserver.core.dao.proto.AttributesMapProto.AttributesMap prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.zibea.recommendations.webserver.core.dao.proto.AttributesMapProto.AttributesMapOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return internal_static_com_zibea_recommendations_webserver_dataaccess_proto_AttributesMap_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return internal_static_com_zibea_recommendations_webserver_dataaccess_proto_AttributesMap_fieldAccessorTable;
      }

      // Construct using com.zibea.recommendations.webserver.core.dao.proto.AttributesMapProto.AttributesMap.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getAttributesFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        if (attributesBuilder_ == null) {
          attributes_ = com.zibea.recommendations.webserver.core.dao.proto.AttributesMapProto.Map.getDefaultInstance();
        } else {
          attributesBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.zibea.recommendations.webserver.core.dao.proto.AttributesMapProto.AttributesMap.getDescriptor();
      }

      public com.zibea.recommendations.webserver.core.dao.proto.AttributesMapProto.AttributesMap getDefaultInstanceForType() {
        return getDefaultInstance();
      }

      public com.zibea.recommendations.webserver.core.dao.proto.AttributesMapProto.AttributesMap build() {
        com.zibea.recommendations.webserver.core.dao.proto.AttributesMapProto.AttributesMap result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      private com.zibea.recommendations.webserver.core.dao.proto.AttributesMapProto.AttributesMap buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        com.zibea.recommendations.webserver.core.dao.proto.AttributesMapProto.AttributesMap result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }

      public com.zibea.recommendations.webserver.core.dao.proto.AttributesMapProto.AttributesMap buildPartial() {
        com.zibea.recommendations.webserver.core.dao.proto.AttributesMapProto.AttributesMap result = new com.zibea.recommendations.webserver.core.dao.proto.AttributesMapProto.AttributesMap(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        if (attributesBuilder_ == null) {
          result.attributes_ = attributes_;
        } else {
          result.attributes_ = attributesBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.zibea.recommendations.webserver.core.dao.proto.AttributesMapProto.AttributesMap) {
          return mergeFrom((com.zibea.recommendations.webserver.core.dao.proto.AttributesMapProto.AttributesMap)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.zibea.recommendations.webserver.core.dao.proto.AttributesMapProto.AttributesMap other) {
        if (other == getDefaultInstance()) return this;
        if (other.hasAttributes()) {
          mergeAttributes(other.getAttributes());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasAttributes()) {

          return false;
        }
        if (!getAttributes().isInitialized()) {

          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 10: {
              com.zibea.recommendations.webserver.core.dao.proto.AttributesMapProto.Map.Builder subBuilder = com.zibea.recommendations.webserver.core.dao.proto.AttributesMapProto.Map.newBuilder();
              if (hasAttributes()) {
                subBuilder.mergeFrom(getAttributes());
              }
              input.readMessage(subBuilder, extensionRegistry);
              setAttributes(subBuilder.buildPartial());
              break;
            }
          }
        }
      }

      private int bitField0_;

      // required .com.zibea.recommendations.webserver.dataaccess.proto.Map attributes = 1;
      private com.zibea.recommendations.webserver.core.dao.proto.AttributesMapProto.Map attributes_ = com.zibea.recommendations.webserver.core.dao.proto.AttributesMapProto.Map.getDefaultInstance();
      private com.google.protobuf.SingleFieldBuilder<
          com.zibea.recommendations.webserver.core.dao.proto.AttributesMapProto.Map, com.zibea.recommendations.webserver.core.dao.proto.AttributesMapProto.Map.Builder, com.zibea.recommendations.webserver.core.dao.proto.AttributesMapProto.MapOrBuilder> attributesBuilder_;
      public boolean hasAttributes() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public com.zibea.recommendations.webserver.core.dao.proto.AttributesMapProto.Map getAttributes() {
        if (attributesBuilder_ == null) {
          return attributes_;
        } else {
          return attributesBuilder_.getMessage();
        }
      }
      public Builder setAttributes(com.zibea.recommendations.webserver.core.dao.proto.AttributesMapProto.Map value) {
        if (attributesBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          attributes_ = value;
          onChanged();
        } else {
          attributesBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      public Builder setAttributes(
          com.zibea.recommendations.webserver.core.dao.proto.AttributesMapProto.Map.Builder builderForValue) {
        if (attributesBuilder_ == null) {
          attributes_ = builderForValue.build();
          onChanged();
        } else {
          attributesBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      public Builder mergeAttributes(com.zibea.recommendations.webserver.core.dao.proto.AttributesMapProto.Map value) {
        if (attributesBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001) &&
              attributes_ != com.zibea.recommendations.webserver.core.dao.proto.AttributesMapProto.Map.getDefaultInstance()) {
            attributes_ =
              com.zibea.recommendations.webserver.core.dao.proto.AttributesMapProto.Map.newBuilder(attributes_).mergeFrom(value).buildPartial();
          } else {
            attributes_ = value;
          }
          onChanged();
        } else {
          attributesBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      public Builder clearAttributes() {
        if (attributesBuilder_ == null) {
          attributes_ = com.zibea.recommendations.webserver.core.dao.proto.AttributesMapProto.Map.getDefaultInstance();
          onChanged();
        } else {
          attributesBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }
      public com.zibea.recommendations.webserver.core.dao.proto.AttributesMapProto.Map.Builder getAttributesBuilder() {
        bitField0_ |= 0x00000001;
        onChanged();
        return getAttributesFieldBuilder().getBuilder();
      }
      public com.zibea.recommendations.webserver.core.dao.proto.AttributesMapProto.MapOrBuilder getAttributesOrBuilder() {
        if (attributesBuilder_ != null) {
          return attributesBuilder_.getMessageOrBuilder();
        } else {
          return attributes_;
        }
      }
      private com.google.protobuf.SingleFieldBuilder<
          com.zibea.recommendations.webserver.core.dao.proto.AttributesMapProto.Map, com.zibea.recommendations.webserver.core.dao.proto.AttributesMapProto.Map.Builder, com.zibea.recommendations.webserver.core.dao.proto.AttributesMapProto.MapOrBuilder>
          getAttributesFieldBuilder() {
        if (attributesBuilder_ == null) {
          attributesBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              com.zibea.recommendations.webserver.core.dao.proto.AttributesMapProto.Map, com.zibea.recommendations.webserver.core.dao.proto.AttributesMapProto.Map.Builder, com.zibea.recommendations.webserver.core.dao.proto.AttributesMapProto.MapOrBuilder>(
                  attributes_,
                  getParentForChildren(),
                  isClean());
          attributes_ = null;
        }
        return attributesBuilder_;
      }

      // @@protoc_insertion_point(builder_scope:com.zibea.recommendations.webserver.dataaccess.proto.AttributesMap)
    }

    static {
      defaultInstance = new AttributesMap(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:com.zibea.recommendations.webserver.dataaccess.proto.AttributesMap)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_com_zibea_recommendations_webserver_dataaccess_proto_Map_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_zibea_recommendations_webserver_dataaccess_proto_Map_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_com_zibea_recommendations_webserver_dataaccess_proto_Map_KeyValue_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_zibea_recommendations_webserver_dataaccess_proto_Map_KeyValue_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_com_zibea_recommendations_webserver_dataaccess_proto_AttributesMap_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_zibea_recommendations_webserver_dataaccess_proto_AttributesMap_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\023AttributesMap.proto\0224com.zibea.recomme" +
      "ndations.webserver.dataaccess.proto\"\200\001\n\003" +
      "Map\022Q\n\005nodes\030\001 \003(\0132B.com.zibea.recommend" +
      "ations.webserver.dataaccess.proto.Map.Ke" +
      "yValue\032&\n\010KeyValue\022\013\n\003key\030\001 \002(\005\022\r\n\005value" +
      "\030\002 \002(\t\"^\n\rAttributesMap\022M\n\nattributes\030\001 " +
      "\002(\01329.com.zibea.recommendations.webserve" +
      "r.dataaccess.proto.MapBJ\n4com.zibea.reco" +
      "mmendations.webserver.dataaccess.protoB\022" +
      "AttributesMapProto"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_com_zibea_recommendations_webserver_dataaccess_proto_Map_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_com_zibea_recommendations_webserver_dataaccess_proto_Map_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_com_zibea_recommendations_webserver_dataaccess_proto_Map_descriptor,
              new String[] { "Nodes", },
              com.zibea.recommendations.webserver.core.dao.proto.AttributesMapProto.Map.class,
              com.zibea.recommendations.webserver.core.dao.proto.AttributesMapProto.Map.Builder.class);
          internal_static_com_zibea_recommendations_webserver_dataaccess_proto_Map_KeyValue_descriptor =
            internal_static_com_zibea_recommendations_webserver_dataaccess_proto_Map_descriptor.getNestedTypes().get(0);
          internal_static_com_zibea_recommendations_webserver_dataaccess_proto_Map_KeyValue_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_com_zibea_recommendations_webserver_dataaccess_proto_Map_KeyValue_descriptor,
              new String[] { "Key", "Value", },
              com.zibea.recommendations.webserver.core.dao.proto.AttributesMapProto.Map.KeyValue.class,
              com.zibea.recommendations.webserver.core.dao.proto.AttributesMapProto.Map.KeyValue.Builder.class);
          internal_static_com_zibea_recommendations_webserver_dataaccess_proto_AttributesMap_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_com_zibea_recommendations_webserver_dataaccess_proto_AttributesMap_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_com_zibea_recommendations_webserver_dataaccess_proto_AttributesMap_descriptor,
              new String[] { "Attributes", },
              com.zibea.recommendations.webserver.core.dao.proto.AttributesMapProto.AttributesMap.class,
              com.zibea.recommendations.webserver.core.dao.proto.AttributesMapProto.AttributesMap.Builder.class);
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }
  
  // @@protoc_insertion_point(outer_class_scope)
}
