// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ItemParametersProto.proto

package com.zibea.recommendations.services.partner.dao.impl.proto;

public final class ItemParametersProto {
  private ItemParametersProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface ParametersOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // repeated .com.zibea.recommendations.services.partner.dao.impl.proto.Parameters.Parameter param = 1;
    java.util.List<com.zibea.recommendations.services.partner.dao.impl.proto.ItemParametersProto.Parameters.Parameter> 
        getParamList();
    com.zibea.recommendations.services.partner.dao.impl.proto.ItemParametersProto.Parameters.Parameter getParam(int index);
    int getParamCount();
    java.util.List<? extends com.zibea.recommendations.services.partner.dao.impl.proto.ItemParametersProto.Parameters.ParameterOrBuilder> 
        getParamOrBuilderList();
    com.zibea.recommendations.services.partner.dao.impl.proto.ItemParametersProto.Parameters.ParameterOrBuilder getParamOrBuilder(
        int index);
  }
  public static final class Parameters extends
      com.google.protobuf.GeneratedMessage
      implements ParametersOrBuilder {
    // Use Parameters.newBuilder() to construct.
    private Parameters(Builder builder) {
      super(builder);
    }
    private Parameters(boolean noInit) {}
    
    private static final Parameters defaultInstance;
    public static Parameters getDefaultInstance() {
      return defaultInstance;
    }
    
    public Parameters getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.zibea.recommendations.services.partner.dao.impl.proto.ItemParametersProto.internal_static_com_zibea_recommendations_services_partner_dao_impl_proto_Parameters_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.zibea.recommendations.services.partner.dao.impl.proto.ItemParametersProto.internal_static_com_zibea_recommendations_services_partner_dao_impl_proto_Parameters_fieldAccessorTable;
    }
    
    public interface ParameterOrBuilder
        extends com.google.protobuf.MessageOrBuilder {
      
      // required string key = 1;
      boolean hasKey();
      String getKey();
      
      // required string value = 2;
      boolean hasValue();
      String getValue();
      
      // optional string unit = 3;
      boolean hasUnit();
      String getUnit();
    }
    public static final class Parameter extends
        com.google.protobuf.GeneratedMessage
        implements ParameterOrBuilder {
      // Use Parameter.newBuilder() to construct.
      private Parameter(Builder builder) {
        super(builder);
      }
      private Parameter(boolean noInit) {}
      
      private static final Parameter defaultInstance;
      public static Parameter getDefaultInstance() {
        return defaultInstance;
      }
      
      public Parameter getDefaultInstanceForType() {
        return defaultInstance;
      }
      
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.zibea.recommendations.services.partner.dao.impl.proto.ItemParametersProto.internal_static_com_zibea_recommendations_services_partner_dao_impl_proto_Parameters_Parameter_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.zibea.recommendations.services.partner.dao.impl.proto.ItemParametersProto.internal_static_com_zibea_recommendations_services_partner_dao_impl_proto_Parameters_Parameter_fieldAccessorTable;
      }
      
      private int bitField0_;
      // required string key = 1;
      public static final int KEY_FIELD_NUMBER = 1;
      private java.lang.Object key_;
      public boolean hasKey() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public String getKey() {
        java.lang.Object ref = key_;
        if (ref instanceof String) {
          return (String) ref;
        } else {
          com.google.protobuf.ByteString bs = 
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          if (com.google.protobuf.Internal.isValidUtf8(bs)) {
            key_ = s;
          }
          return s;
        }
      }
      private com.google.protobuf.ByteString getKeyBytes() {
        java.lang.Object ref = key_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8((String) ref);
          key_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      
      // required string value = 2;
      public static final int VALUE_FIELD_NUMBER = 2;
      private java.lang.Object value_;
      public boolean hasValue() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      public String getValue() {
        java.lang.Object ref = value_;
        if (ref instanceof String) {
          return (String) ref;
        } else {
          com.google.protobuf.ByteString bs = 
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          if (com.google.protobuf.Internal.isValidUtf8(bs)) {
            value_ = s;
          }
          return s;
        }
      }
      private com.google.protobuf.ByteString getValueBytes() {
        java.lang.Object ref = value_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8((String) ref);
          value_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      
      // optional string unit = 3;
      public static final int UNIT_FIELD_NUMBER = 3;
      private java.lang.Object unit_;
      public boolean hasUnit() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      public String getUnit() {
        java.lang.Object ref = unit_;
        if (ref instanceof String) {
          return (String) ref;
        } else {
          com.google.protobuf.ByteString bs = 
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          if (com.google.protobuf.Internal.isValidUtf8(bs)) {
            unit_ = s;
          }
          return s;
        }
      }
      private com.google.protobuf.ByteString getUnitBytes() {
        java.lang.Object ref = unit_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8((String) ref);
          unit_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      
      private void initFields() {
        key_ = "";
        value_ = "";
        unit_ = "";
      }
      private byte memoizedIsInitialized = -1;
      public final boolean isInitialized() {
        byte isInitialized = memoizedIsInitialized;
        if (isInitialized != -1) return isInitialized == 1;
        
        if (!hasKey()) {
          memoizedIsInitialized = 0;
          return false;
        }
        if (!hasValue()) {
          memoizedIsInitialized = 0;
          return false;
        }
        memoizedIsInitialized = 1;
        return true;
      }
      
      public void writeTo(com.google.protobuf.CodedOutputStream output)
                          throws java.io.IOException {
        getSerializedSize();
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          output.writeBytes(1, getKeyBytes());
        }
        if (((bitField0_ & 0x00000002) == 0x00000002)) {
          output.writeBytes(2, getValueBytes());
        }
        if (((bitField0_ & 0x00000004) == 0x00000004)) {
          output.writeBytes(3, getUnitBytes());
        }
        getUnknownFields().writeTo(output);
      }
      
      private int memoizedSerializedSize = -1;
      public int getSerializedSize() {
        int size = memoizedSerializedSize;
        if (size != -1) return size;
      
        size = 0;
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          size += com.google.protobuf.CodedOutputStream
            .computeBytesSize(1, getKeyBytes());
        }
        if (((bitField0_ & 0x00000002) == 0x00000002)) {
          size += com.google.protobuf.CodedOutputStream
            .computeBytesSize(2, getValueBytes());
        }
        if (((bitField0_ & 0x00000004) == 0x00000004)) {
          size += com.google.protobuf.CodedOutputStream
            .computeBytesSize(3, getUnitBytes());
        }
        size += getUnknownFields().getSerializedSize();
        memoizedSerializedSize = size;
        return size;
      }
      
      private static final long serialVersionUID = 0L;
      @java.lang.Override
      protected java.lang.Object writeReplace()
          throws java.io.ObjectStreamException {
        return super.writeReplace();
      }
      
      public static com.zibea.recommendations.services.partner.dao.impl.proto.ItemParametersProto.Parameters.Parameter parseFrom(
          com.google.protobuf.ByteString data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return newBuilder().mergeFrom(data).buildParsed();
      }
      public static com.zibea.recommendations.services.partner.dao.impl.proto.ItemParametersProto.Parameters.Parameter parseFrom(
          com.google.protobuf.ByteString data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return newBuilder().mergeFrom(data, extensionRegistry)
                 .buildParsed();
      }
      public static com.zibea.recommendations.services.partner.dao.impl.proto.ItemParametersProto.Parameters.Parameter parseFrom(byte[] data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return newBuilder().mergeFrom(data).buildParsed();
      }
      public static com.zibea.recommendations.services.partner.dao.impl.proto.ItemParametersProto.Parameters.Parameter parseFrom(
          byte[] data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return newBuilder().mergeFrom(data, extensionRegistry)
                 .buildParsed();
      }
      public static com.zibea.recommendations.services.partner.dao.impl.proto.ItemParametersProto.Parameters.Parameter parseFrom(java.io.InputStream input)
          throws java.io.IOException {
        return newBuilder().mergeFrom(input).buildParsed();
      }
      public static com.zibea.recommendations.services.partner.dao.impl.proto.ItemParametersProto.Parameters.Parameter parseFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return newBuilder().mergeFrom(input, extensionRegistry)
                 .buildParsed();
      }
      public static com.zibea.recommendations.services.partner.dao.impl.proto.ItemParametersProto.Parameters.Parameter parseDelimitedFrom(java.io.InputStream input)
          throws java.io.IOException {
        Builder builder = newBuilder();
        if (builder.mergeDelimitedFrom(input)) {
          return builder.buildParsed();
        } else {
          return null;
        }
      }
      public static com.zibea.recommendations.services.partner.dao.impl.proto.ItemParametersProto.Parameters.Parameter parseDelimitedFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        Builder builder = newBuilder();
        if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
          return builder.buildParsed();
        } else {
          return null;
        }
      }
      public static com.zibea.recommendations.services.partner.dao.impl.proto.ItemParametersProto.Parameters.Parameter parseFrom(
          com.google.protobuf.CodedInputStream input)
          throws java.io.IOException {
        return newBuilder().mergeFrom(input).buildParsed();
      }
      public static com.zibea.recommendations.services.partner.dao.impl.proto.ItemParametersProto.Parameters.Parameter parseFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return newBuilder().mergeFrom(input, extensionRegistry)
                 .buildParsed();
      }
      
      public static Builder newBuilder() { return Builder.create(); }
      public Builder newBuilderForType() { return newBuilder(); }
      public static Builder newBuilder(com.zibea.recommendations.services.partner.dao.impl.proto.ItemParametersProto.Parameters.Parameter prototype) {
        return newBuilder().mergeFrom(prototype);
      }
      public Builder toBuilder() { return newBuilder(this); }
      
      @java.lang.Override
      protected Builder newBuilderForType(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        Builder builder = new Builder(parent);
        return builder;
      }
      public static final class Builder extends
          com.google.protobuf.GeneratedMessage.Builder<Builder>
         implements com.zibea.recommendations.services.partner.dao.impl.proto.ItemParametersProto.Parameters.ParameterOrBuilder {
        public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
          return com.zibea.recommendations.services.partner.dao.impl.proto.ItemParametersProto.internal_static_com_zibea_recommendations_services_partner_dao_impl_proto_Parameters_Parameter_descriptor;
        }
        
        protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
            internalGetFieldAccessorTable() {
          return com.zibea.recommendations.services.partner.dao.impl.proto.ItemParametersProto.internal_static_com_zibea_recommendations_services_partner_dao_impl_proto_Parameters_Parameter_fieldAccessorTable;
        }
        
        // Construct using com.zibea.recommendations.services.partner.dao.impl.proto.ItemParametersProto.Parameters.Parameter.newBuilder()
        private Builder() {
          maybeForceBuilderInitialization();
        }
        
        private Builder(BuilderParent parent) {
          super(parent);
          maybeForceBuilderInitialization();
        }
        private void maybeForceBuilderInitialization() {
          if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          }
        }
        private static Builder create() {
          return new Builder();
        }
        
        public Builder clear() {
          super.clear();
          key_ = "";
          bitField0_ = (bitField0_ & ~0x00000001);
          value_ = "";
          bitField0_ = (bitField0_ & ~0x00000002);
          unit_ = "";
          bitField0_ = (bitField0_ & ~0x00000004);
          return this;
        }
        
        public Builder clone() {
          return create().mergeFrom(buildPartial());
        }
        
        public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
          return com.zibea.recommendations.services.partner.dao.impl.proto.ItemParametersProto.Parameters.Parameter.getDescriptor();
        }
        
        public com.zibea.recommendations.services.partner.dao.impl.proto.ItemParametersProto.Parameters.Parameter getDefaultInstanceForType() {
          return com.zibea.recommendations.services.partner.dao.impl.proto.ItemParametersProto.Parameters.Parameter.getDefaultInstance();
        }
        
        public com.zibea.recommendations.services.partner.dao.impl.proto.ItemParametersProto.Parameters.Parameter build() {
          com.zibea.recommendations.services.partner.dao.impl.proto.ItemParametersProto.Parameters.Parameter result = buildPartial();
          if (!result.isInitialized()) {
            throw newUninitializedMessageException(result);
          }
          return result;
        }
        
        private com.zibea.recommendations.services.partner.dao.impl.proto.ItemParametersProto.Parameters.Parameter buildParsed()
            throws com.google.protobuf.InvalidProtocolBufferException {
          com.zibea.recommendations.services.partner.dao.impl.proto.ItemParametersProto.Parameters.Parameter result = buildPartial();
          if (!result.isInitialized()) {
            throw newUninitializedMessageException(
              result).asInvalidProtocolBufferException();
          }
          return result;
        }
        
        public com.zibea.recommendations.services.partner.dao.impl.proto.ItemParametersProto.Parameters.Parameter buildPartial() {
          com.zibea.recommendations.services.partner.dao.impl.proto.ItemParametersProto.Parameters.Parameter result = new com.zibea.recommendations.services.partner.dao.impl.proto.ItemParametersProto.Parameters.Parameter(this);
          int from_bitField0_ = bitField0_;
          int to_bitField0_ = 0;
          if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
            to_bitField0_ |= 0x00000001;
          }
          result.key_ = key_;
          if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
            to_bitField0_ |= 0x00000002;
          }
          result.value_ = value_;
          if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
            to_bitField0_ |= 0x00000004;
          }
          result.unit_ = unit_;
          result.bitField0_ = to_bitField0_;
          onBuilt();
          return result;
        }
        
        public Builder mergeFrom(com.google.protobuf.Message other) {
          if (other instanceof com.zibea.recommendations.services.partner.dao.impl.proto.ItemParametersProto.Parameters.Parameter) {
            return mergeFrom((com.zibea.recommendations.services.partner.dao.impl.proto.ItemParametersProto.Parameters.Parameter)other);
          } else {
            super.mergeFrom(other);
            return this;
          }
        }
        
        public Builder mergeFrom(com.zibea.recommendations.services.partner.dao.impl.proto.ItemParametersProto.Parameters.Parameter other) {
          if (other == com.zibea.recommendations.services.partner.dao.impl.proto.ItemParametersProto.Parameters.Parameter.getDefaultInstance()) return this;
          if (other.hasKey()) {
            setKey(other.getKey());
          }
          if (other.hasValue()) {
            setValue(other.getValue());
          }
          if (other.hasUnit()) {
            setUnit(other.getUnit());
          }
          this.mergeUnknownFields(other.getUnknownFields());
          return this;
        }
        
        public final boolean isInitialized() {
          if (!hasKey()) {
            
            return false;
          }
          if (!hasValue()) {
            
            return false;
          }
          return true;
        }
        
        public Builder mergeFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
          com.google.protobuf.UnknownFieldSet.Builder unknownFields =
            com.google.protobuf.UnknownFieldSet.newBuilder(
              this.getUnknownFields());
          while (true) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              default: {
                if (!parseUnknownField(input, unknownFields,
                                       extensionRegistry, tag)) {
                  this.setUnknownFields(unknownFields.build());
                  onChanged();
                  return this;
                }
                break;
              }
              case 10: {
                bitField0_ |= 0x00000001;
                key_ = input.readBytes();
                break;
              }
              case 18: {
                bitField0_ |= 0x00000002;
                value_ = input.readBytes();
                break;
              }
              case 26: {
                bitField0_ |= 0x00000004;
                unit_ = input.readBytes();
                break;
              }
            }
          }
        }
        
        private int bitField0_;
        
        // required string key = 1;
        private java.lang.Object key_ = "";
        public boolean hasKey() {
          return ((bitField0_ & 0x00000001) == 0x00000001);
        }
        public String getKey() {
          java.lang.Object ref = key_;
          if (!(ref instanceof String)) {
            String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
            key_ = s;
            return s;
          } else {
            return (String) ref;
          }
        }
        public Builder setKey(String value) {
          if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
          key_ = value;
          onChanged();
          return this;
        }
        public Builder clearKey() {
          bitField0_ = (bitField0_ & ~0x00000001);
          key_ = getDefaultInstance().getKey();
          onChanged();
          return this;
        }
        void setKey(com.google.protobuf.ByteString value) {
          bitField0_ |= 0x00000001;
          key_ = value;
          onChanged();
        }
        
        // required string value = 2;
        private java.lang.Object value_ = "";
        public boolean hasValue() {
          return ((bitField0_ & 0x00000002) == 0x00000002);
        }
        public String getValue() {
          java.lang.Object ref = value_;
          if (!(ref instanceof String)) {
            String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
            value_ = s;
            return s;
          } else {
            return (String) ref;
          }
        }
        public Builder setValue(String value) {
          if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
          value_ = value;
          onChanged();
          return this;
        }
        public Builder clearValue() {
          bitField0_ = (bitField0_ & ~0x00000002);
          value_ = getDefaultInstance().getValue();
          onChanged();
          return this;
        }
        void setValue(com.google.protobuf.ByteString value) {
          bitField0_ |= 0x00000002;
          value_ = value;
          onChanged();
        }
        
        // optional string unit = 3;
        private java.lang.Object unit_ = "";
        public boolean hasUnit() {
          return ((bitField0_ & 0x00000004) == 0x00000004);
        }
        public String getUnit() {
          java.lang.Object ref = unit_;
          if (!(ref instanceof String)) {
            String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
            unit_ = s;
            return s;
          } else {
            return (String) ref;
          }
        }
        public Builder setUnit(String value) {
          if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
          unit_ = value;
          onChanged();
          return this;
        }
        public Builder clearUnit() {
          bitField0_ = (bitField0_ & ~0x00000004);
          unit_ = getDefaultInstance().getUnit();
          onChanged();
          return this;
        }
        void setUnit(com.google.protobuf.ByteString value) {
          bitField0_ |= 0x00000004;
          unit_ = value;
          onChanged();
        }
        
        // @@protoc_insertion_point(builder_scope:com.zibea.recommendations.services.partner.dao.impl.proto.Parameters.Parameter)
      }
      
      static {
        defaultInstance = new Parameter(true);
        defaultInstance.initFields();
      }
      
      // @@protoc_insertion_point(class_scope:com.zibea.recommendations.services.partner.dao.impl.proto.Parameters.Parameter)
    }
    
    // repeated .com.zibea.recommendations.services.partner.dao.impl.proto.Parameters.Parameter param = 1;
    public static final int PARAM_FIELD_NUMBER = 1;
    private java.util.List<com.zibea.recommendations.services.partner.dao.impl.proto.ItemParametersProto.Parameters.Parameter> param_;
    public java.util.List<com.zibea.recommendations.services.partner.dao.impl.proto.ItemParametersProto.Parameters.Parameter> getParamList() {
      return param_;
    }
    public java.util.List<? extends com.zibea.recommendations.services.partner.dao.impl.proto.ItemParametersProto.Parameters.ParameterOrBuilder> 
        getParamOrBuilderList() {
      return param_;
    }
    public int getParamCount() {
      return param_.size();
    }
    public com.zibea.recommendations.services.partner.dao.impl.proto.ItemParametersProto.Parameters.Parameter getParam(int index) {
      return param_.get(index);
    }
    public com.zibea.recommendations.services.partner.dao.impl.proto.ItemParametersProto.Parameters.ParameterOrBuilder getParamOrBuilder(
        int index) {
      return param_.get(index);
    }
    
    private void initFields() {
      param_ = java.util.Collections.emptyList();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      for (int i = 0; i < getParamCount(); i++) {
        if (!getParam(i).isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      for (int i = 0; i < param_.size(); i++) {
        output.writeMessage(1, param_.get(i));
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      for (int i = 0; i < param_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, param_.get(i));
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static com.zibea.recommendations.services.partner.dao.impl.proto.ItemParametersProto.Parameters parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.zibea.recommendations.services.partner.dao.impl.proto.ItemParametersProto.Parameters parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.zibea.recommendations.services.partner.dao.impl.proto.ItemParametersProto.Parameters parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.zibea.recommendations.services.partner.dao.impl.proto.ItemParametersProto.Parameters parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.zibea.recommendations.services.partner.dao.impl.proto.ItemParametersProto.Parameters parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.zibea.recommendations.services.partner.dao.impl.proto.ItemParametersProto.Parameters parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.zibea.recommendations.services.partner.dao.impl.proto.ItemParametersProto.Parameters parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.zibea.recommendations.services.partner.dao.impl.proto.ItemParametersProto.Parameters parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.zibea.recommendations.services.partner.dao.impl.proto.ItemParametersProto.Parameters parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.zibea.recommendations.services.partner.dao.impl.proto.ItemParametersProto.Parameters parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.zibea.recommendations.services.partner.dao.impl.proto.ItemParametersProto.Parameters prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.zibea.recommendations.services.partner.dao.impl.proto.ItemParametersProto.ParametersOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.zibea.recommendations.services.partner.dao.impl.proto.ItemParametersProto.internal_static_com_zibea_recommendations_services_partner_dao_impl_proto_Parameters_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.zibea.recommendations.services.partner.dao.impl.proto.ItemParametersProto.internal_static_com_zibea_recommendations_services_partner_dao_impl_proto_Parameters_fieldAccessorTable;
      }
      
      // Construct using com.zibea.recommendations.services.partner.dao.impl.proto.ItemParametersProto.Parameters.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getParamFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        if (paramBuilder_ == null) {
          param_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          paramBuilder_.clear();
        }
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.zibea.recommendations.services.partner.dao.impl.proto.ItemParametersProto.Parameters.getDescriptor();
      }
      
      public com.zibea.recommendations.services.partner.dao.impl.proto.ItemParametersProto.Parameters getDefaultInstanceForType() {
        return com.zibea.recommendations.services.partner.dao.impl.proto.ItemParametersProto.Parameters.getDefaultInstance();
      }
      
      public com.zibea.recommendations.services.partner.dao.impl.proto.ItemParametersProto.Parameters build() {
        com.zibea.recommendations.services.partner.dao.impl.proto.ItemParametersProto.Parameters result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private com.zibea.recommendations.services.partner.dao.impl.proto.ItemParametersProto.Parameters buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        com.zibea.recommendations.services.partner.dao.impl.proto.ItemParametersProto.Parameters result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public com.zibea.recommendations.services.partner.dao.impl.proto.ItemParametersProto.Parameters buildPartial() {
        com.zibea.recommendations.services.partner.dao.impl.proto.ItemParametersProto.Parameters result = new com.zibea.recommendations.services.partner.dao.impl.proto.ItemParametersProto.Parameters(this);
        int from_bitField0_ = bitField0_;
        if (paramBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001)) {
            param_ = java.util.Collections.unmodifiableList(param_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.param_ = param_;
        } else {
          result.param_ = paramBuilder_.build();
        }
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.zibea.recommendations.services.partner.dao.impl.proto.ItemParametersProto.Parameters) {
          return mergeFrom((com.zibea.recommendations.services.partner.dao.impl.proto.ItemParametersProto.Parameters)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(com.zibea.recommendations.services.partner.dao.impl.proto.ItemParametersProto.Parameters other) {
        if (other == com.zibea.recommendations.services.partner.dao.impl.proto.ItemParametersProto.Parameters.getDefaultInstance()) return this;
        if (paramBuilder_ == null) {
          if (!other.param_.isEmpty()) {
            if (param_.isEmpty()) {
              param_ = other.param_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureParamIsMutable();
              param_.addAll(other.param_);
            }
            onChanged();
          }
        } else {
          if (!other.param_.isEmpty()) {
            if (paramBuilder_.isEmpty()) {
              paramBuilder_.dispose();
              paramBuilder_ = null;
              param_ = other.param_;
              bitField0_ = (bitField0_ & ~0x00000001);
              paramBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getParamFieldBuilder() : null;
            } else {
              paramBuilder_.addAllMessages(other.param_);
            }
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        for (int i = 0; i < getParamCount(); i++) {
          if (!getParam(i).isInitialized()) {
            
            return false;
          }
        }
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 10: {
              com.zibea.recommendations.services.partner.dao.impl.proto.ItemParametersProto.Parameters.Parameter.Builder subBuilder = com.zibea.recommendations.services.partner.dao.impl.proto.ItemParametersProto.Parameters.Parameter.newBuilder();
              input.readMessage(subBuilder, extensionRegistry);
              addParam(subBuilder.buildPartial());
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // repeated .com.zibea.recommendations.services.partner.dao.impl.proto.Parameters.Parameter param = 1;
      private java.util.List<com.zibea.recommendations.services.partner.dao.impl.proto.ItemParametersProto.Parameters.Parameter> param_ =
        java.util.Collections.emptyList();
      private void ensureParamIsMutable() {
        if (!((bitField0_ & 0x00000001) == 0x00000001)) {
          param_ = new java.util.ArrayList<com.zibea.recommendations.services.partner.dao.impl.proto.ItemParametersProto.Parameters.Parameter>(param_);
          bitField0_ |= 0x00000001;
         }
      }
      
      private com.google.protobuf.RepeatedFieldBuilder<
          com.zibea.recommendations.services.partner.dao.impl.proto.ItemParametersProto.Parameters.Parameter, com.zibea.recommendations.services.partner.dao.impl.proto.ItemParametersProto.Parameters.Parameter.Builder, com.zibea.recommendations.services.partner.dao.impl.proto.ItemParametersProto.Parameters.ParameterOrBuilder> paramBuilder_;
      
      public java.util.List<com.zibea.recommendations.services.partner.dao.impl.proto.ItemParametersProto.Parameters.Parameter> getParamList() {
        if (paramBuilder_ == null) {
          return java.util.Collections.unmodifiableList(param_);
        } else {
          return paramBuilder_.getMessageList();
        }
      }
      public int getParamCount() {
        if (paramBuilder_ == null) {
          return param_.size();
        } else {
          return paramBuilder_.getCount();
        }
      }
      public com.zibea.recommendations.services.partner.dao.impl.proto.ItemParametersProto.Parameters.Parameter getParam(int index) {
        if (paramBuilder_ == null) {
          return param_.get(index);
        } else {
          return paramBuilder_.getMessage(index);
        }
      }
      public Builder setParam(
          int index, com.zibea.recommendations.services.partner.dao.impl.proto.ItemParametersProto.Parameters.Parameter value) {
        if (paramBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureParamIsMutable();
          param_.set(index, value);
          onChanged();
        } else {
          paramBuilder_.setMessage(index, value);
        }
        return this;
      }
      public Builder setParam(
          int index, com.zibea.recommendations.services.partner.dao.impl.proto.ItemParametersProto.Parameters.Parameter.Builder builderForValue) {
        if (paramBuilder_ == null) {
          ensureParamIsMutable();
          param_.set(index, builderForValue.build());
          onChanged();
        } else {
          paramBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      public Builder addParam(com.zibea.recommendations.services.partner.dao.impl.proto.ItemParametersProto.Parameters.Parameter value) {
        if (paramBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureParamIsMutable();
          param_.add(value);
          onChanged();
        } else {
          paramBuilder_.addMessage(value);
        }
        return this;
      }
      public Builder addParam(
          int index, com.zibea.recommendations.services.partner.dao.impl.proto.ItemParametersProto.Parameters.Parameter value) {
        if (paramBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureParamIsMutable();
          param_.add(index, value);
          onChanged();
        } else {
          paramBuilder_.addMessage(index, value);
        }
        return this;
      }
      public Builder addParam(
          com.zibea.recommendations.services.partner.dao.impl.proto.ItemParametersProto.Parameters.Parameter.Builder builderForValue) {
        if (paramBuilder_ == null) {
          ensureParamIsMutable();
          param_.add(builderForValue.build());
          onChanged();
        } else {
          paramBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      public Builder addParam(
          int index, com.zibea.recommendations.services.partner.dao.impl.proto.ItemParametersProto.Parameters.Parameter.Builder builderForValue) {
        if (paramBuilder_ == null) {
          ensureParamIsMutable();
          param_.add(index, builderForValue.build());
          onChanged();
        } else {
          paramBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      public Builder addAllParam(
          java.lang.Iterable<? extends com.zibea.recommendations.services.partner.dao.impl.proto.ItemParametersProto.Parameters.Parameter> values) {
        if (paramBuilder_ == null) {
          ensureParamIsMutable();
          super.addAll(values, param_);
          onChanged();
        } else {
          paramBuilder_.addAllMessages(values);
        }
        return this;
      }
      public Builder clearParam() {
        if (paramBuilder_ == null) {
          param_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          paramBuilder_.clear();
        }
        return this;
      }
      public Builder removeParam(int index) {
        if (paramBuilder_ == null) {
          ensureParamIsMutable();
          param_.remove(index);
          onChanged();
        } else {
          paramBuilder_.remove(index);
        }
        return this;
      }
      public com.zibea.recommendations.services.partner.dao.impl.proto.ItemParametersProto.Parameters.Parameter.Builder getParamBuilder(
          int index) {
        return getParamFieldBuilder().getBuilder(index);
      }
      public com.zibea.recommendations.services.partner.dao.impl.proto.ItemParametersProto.Parameters.ParameterOrBuilder getParamOrBuilder(
          int index) {
        if (paramBuilder_ == null) {
          return param_.get(index);  } else {
          return paramBuilder_.getMessageOrBuilder(index);
        }
      }
      public java.util.List<? extends com.zibea.recommendations.services.partner.dao.impl.proto.ItemParametersProto.Parameters.ParameterOrBuilder> 
           getParamOrBuilderList() {
        if (paramBuilder_ != null) {
          return paramBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(param_);
        }
      }
      public com.zibea.recommendations.services.partner.dao.impl.proto.ItemParametersProto.Parameters.Parameter.Builder addParamBuilder() {
        return getParamFieldBuilder().addBuilder(
            com.zibea.recommendations.services.partner.dao.impl.proto.ItemParametersProto.Parameters.Parameter.getDefaultInstance());
      }
      public com.zibea.recommendations.services.partner.dao.impl.proto.ItemParametersProto.Parameters.Parameter.Builder addParamBuilder(
          int index) {
        return getParamFieldBuilder().addBuilder(
            index, com.zibea.recommendations.services.partner.dao.impl.proto.ItemParametersProto.Parameters.Parameter.getDefaultInstance());
      }
      public java.util.List<com.zibea.recommendations.services.partner.dao.impl.proto.ItemParametersProto.Parameters.Parameter.Builder> 
           getParamBuilderList() {
        return getParamFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          com.zibea.recommendations.services.partner.dao.impl.proto.ItemParametersProto.Parameters.Parameter, com.zibea.recommendations.services.partner.dao.impl.proto.ItemParametersProto.Parameters.Parameter.Builder, com.zibea.recommendations.services.partner.dao.impl.proto.ItemParametersProto.Parameters.ParameterOrBuilder> 
          getParamFieldBuilder() {
        if (paramBuilder_ == null) {
          paramBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              com.zibea.recommendations.services.partner.dao.impl.proto.ItemParametersProto.Parameters.Parameter, com.zibea.recommendations.services.partner.dao.impl.proto.ItemParametersProto.Parameters.Parameter.Builder, com.zibea.recommendations.services.partner.dao.impl.proto.ItemParametersProto.Parameters.ParameterOrBuilder>(
                  param_,
                  ((bitField0_ & 0x00000001) == 0x00000001),
                  getParentForChildren(),
                  isClean());
          param_ = null;
        }
        return paramBuilder_;
      }
      
      // @@protoc_insertion_point(builder_scope:com.zibea.recommendations.services.partner.dao.impl.proto.Parameters)
    }
    
    static {
      defaultInstance = new Parameters(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:com.zibea.recommendations.services.partner.dao.impl.proto.Parameters)
  }
  
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_com_zibea_recommendations_services_partner_dao_impl_proto_Parameters_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_zibea_recommendations_services_partner_dao_impl_proto_Parameters_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_com_zibea_recommendations_services_partner_dao_impl_proto_Parameters_Parameter_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_zibea_recommendations_services_partner_dao_impl_proto_Parameters_Parameter_fieldAccessorTable;
  
  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\031ItemParametersProto.proto\0229com.zibea.r" +
      "ecommendations.services.partner.dao.impl" +
      ".proto\"\243\001\n\nParameters\022^\n\005param\030\001 \003(\0132O.c" +
      "om.zibea.recommendations.services.partne" +
      "r.dao.impl.proto.Parameters.Parameter\0325\n" +
      "\tParameter\022\013\n\003key\030\001 \002(\t\022\r\n\005value\030\002 \002(\t\022\014" +
      "\n\004unit\030\003 \001(\tBP\n9com.zibea.recommendation" +
      "s.services.partner.dao.impl.protoB\023ItemP" +
      "arametersProto"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_com_zibea_recommendations_services_partner_dao_impl_proto_Parameters_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_com_zibea_recommendations_services_partner_dao_impl_proto_Parameters_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_com_zibea_recommendations_services_partner_dao_impl_proto_Parameters_descriptor,
              new java.lang.String[] { "Param", },
              com.zibea.recommendations.services.partner.dao.impl.proto.ItemParametersProto.Parameters.class,
              com.zibea.recommendations.services.partner.dao.impl.proto.ItemParametersProto.Parameters.Builder.class);
          internal_static_com_zibea_recommendations_services_partner_dao_impl_proto_Parameters_Parameter_descriptor =
            internal_static_com_zibea_recommendations_services_partner_dao_impl_proto_Parameters_descriptor.getNestedTypes().get(0);
          internal_static_com_zibea_recommendations_services_partner_dao_impl_proto_Parameters_Parameter_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_com_zibea_recommendations_services_partner_dao_impl_proto_Parameters_Parameter_descriptor,
              new java.lang.String[] { "Key", "Value", "Unit", },
              com.zibea.recommendations.services.partner.dao.impl.proto.ItemParametersProto.Parameters.Parameter.class,
              com.zibea.recommendations.services.partner.dao.impl.proto.ItemParametersProto.Parameters.Parameter.Builder.class);
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }
  
  // @@protoc_insertion_point(outer_class_scope)
}
